name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      NEXTAUTH_SECRET: "test-secret"
      NEXTAUTH_URL: "http://localhost:3000"
      DATABASE_URL: "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNDhmOWM4Y2UtZDIyOS00ZTZkLWIzMDAtZTE4YzM4ZGRkOTNjIiwidGVuYW50X2lkIjoiMDUyNDlkYzNkM2NmNjk5ZWVhMTQ2NTkwYzZmMzJlODIzMGI2YzljMWI5YWU5ZmMzOWJiYTEyN2QzZDk1MmMwMiIsImludGVybmFsX3NlY3JldCI6ImRmMDk2Mjk2LWIyYmQtNDViYy1iNGYyLTE3ZmE3ZjY2MTJjMCJ9.dhoaMH9a-C0HlovOpDwkGdILB5ug3isUIAva0orSRmM"
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: "dtbk6m3ig"
      NEXT_PUBLIC_CLOUDINARY_API_KEY: "267428251334864"
      CLOUDINARY_API_SECRET: "uWadj6uef4XZGUXxi7whMSKHFaQ"
      NEXT_PUBLIC_UPLOAD_PRESET: "ml_default"
      
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Build application
      run: npm run build
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Start application
      run: npm run start &
    - name: Wait for application to start
      run: |
        timeout=300
        while ! curl -s http://localhost:3000 > /dev/null; do
          sleep 1
          timeout=$((timeout-1))
          if [ $timeout -le 0 ]; then
            echo "Application failed to start"
            exit 1
          fi
        done
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
